version: "3.7"

services:
  app:
      build: .
      container_name: "exec.container"
      ports:
        - "5000"
      environment:
        FLASK_DEBUG: "True"
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app
      ports:
        - "80:80"
