version: "3.7"

services:
  backend:
    build: .
    image: "exec.image"
    container_name: "exec.container"
    port: 8001:5000
    environment:
      FLASK_DEBUG: "True"


  proxy:
    # Your code is here #


  db:
    # Your code is here #


networks:
  # Your code is here #


volumes:
  # Your code is here #
